### ISSUE TITLE
Cannot read property 'datetime' of undefined

### ISSUE THREAD

**Issue by efinst0rm** [starsky135/nhl-discord-bot#3]
Hey,

My log seems to get spammed with this.
`***ERROR***
Technical info: An error has occured. The program will attempt to continue. Please try clearing the cache if you continue to receive this message.
TypeError: Cannot read property 'datetime' of undefined
***ERROR***
Technical info: There was an error.
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
    at C:\Users\Customer\Desktop\Hockey\api.js:159:44
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
***ERROR***
Technical info: There was an error.
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
    at C:\Users\Customer\Desktop\Hockey\api.js:159:44
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
***ERROR***
Technical info: There was an error.
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
    at C:\Users\Customer\Desktop\Hockey\api.js:159:44
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
***ERROR***
Technical info: There was an error.
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
    at C:\Users\Customer\Desktop\Hockey\api.js:159:44
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
***ERROR***
Technical info: There was an error.
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
    at C:\Users\Customer\Desktop\Hockey\api.js:159:44
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
***ERROR***
Technical info: There was an error.
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
***ERROR***
Technical info: TypeError: Cannot read property 'datetime' of undefined
    at C:\Users\Customer\Desktop\Hockey\api.js:159:44
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by starsky135** [comment]
Hey there,

This is an older release of the bot with many bugs and I no longer support it. v3 is much better and was made with improved compatibility for all servers.

I'll be releasing the source for that bot soon.
